---
- hosts: all
  become: yes
  tasks: 
  - name: install tree on ansible ubuntu nodes
    apt:
      name: tree 
      state: present

  - name: install wget on ansible ubuntu nodes
    apt: 
      name: wget
      state: present

  -name: install git software in ubuntu service
  apt:
    name: git
    state: present
    